% Louise Evans (autogenerated script)
function [Selleck]=import_compoundplates()
%% Import the data
[~, ~, raw] = xlsread('W:\2015_09_HTS_LE\project_database\drug_libraries\Results\SelleckBioactives_SMDC_384well_mapping.xlsx','SelleckBioactives_SMDC_384well_');% import selleck bioactive library
raw = raw(2:end,:);%remove headers
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};%clean
cellVectors = raw(:,[3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20]);%clean
raw = raw(:,[1,2,17]);%clean

% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

% Create output variable
data = reshape([raw{:}],size(raw));%reshape

% Create table
SelleckBioactivesSMDC384wellmapping = table;%convert format

% Allocate imported array to column variable names
% Maintain this order in case later code depends on it (bad)
SelleckBioactivesSMDC384wellmapping.SMDC = data(:,1);%numbers
SelleckBioactivesSMDC384wellmapping.LOT = data(:,2);%numbers
SelleckBioactivesSMDC384wellmapping.MW = data(:,3);%numbers

SelleckBioactivesSMDC384wellmapping.Catalog_No = cellVectors(:,1);%text
SelleckBioactivesSMDC384wellmapping.Salt = cellVectors(:,2);%text
SelleckBioactivesSMDC384wellmapping.Solvate = cellVectors(:,3);%text
SelleckBioactivesSMDC384wellmapping.PLATE_96 = cellVectors(:,4);%text
SelleckBioactivesSMDC384wellmapping.WELL_96 = cellVectors(:,5);%text
SelleckBioactivesSMDC384wellmapping.SMDCPROCESSEDSMILES = cellVectors(:,6);%text
SelleckBioactivesSMDC384wellmapping.PLATE_384 = cellVectors(:,7);%text
SelleckBioactivesSMDC384wellmapping.WELL_384 = cellVectors(:,8);%text
SelleckBioactivesSMDC384wellmapping.SMILES = cellVectors(:,9);%text
SelleckBioactivesSMDC384wellmapping.Compound_ID = cellVectors(:,10);%text
SelleckBioactivesSMDC384wellmapping.Target = cellVectors(:,11);%text
SelleckBioactivesSMDC384wellmapping.Pathway = cellVectors(:,12);%text
SelleckBioactivesSMDC384wellmapping.Description = cellVectors(:,13);%text
SelleckBioactivesSMDC384wellmapping.CAS_Number = cellVectors(:,14);%text
SelleckBioactivesSMDC384wellmapping.Form = cellVectors(:,15);%text
SelleckBioactivesSMDC384wellmapping.Plate96 = cellVectors(:,16);%text
SelleckBioactivesSMDC384wellmapping.Well96 = cellVectors(:,17);%text

Selleck = SelleckBioactivesSMDC384wellmapping;%rename

% Clear temporary variables
clearvars data raw cellVectors R SelleckBioactivesSMDC384wellmapping;