%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: W:\2015_09_HTS_LE\project_database\drug_libraries\AW SMDC Drug Libraries Raw Data\DIVIV-NCI-Diversity-1430-AW.xlsx
%    Worksheet: DIVIV-NCI-Diversity-1430-AW-Com
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/02 17:22:18

%% Import the data
[~, ~, raw] = xlsread('W:\2015_09_HTS_LE\project_database\drug_libraries\AW SMDC Drug Libraries Raw Data\DIVIV-NCI-Diversity-1430-AW.xlsx','DIVIV-NCI-Diversity-1430-AW-Com','A2:D1597');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,2);
raw = raw(:,[1,3,4]);

%% Create output variable
data = reshape([raw{:}],size(raw));
Diversity = table;

%% Allocate imported array to column variable names
Diversity.Platenum = data(:,1);
Diversity.WellID = cellVectors(:,1);
Diversity.NSC = data(:,2);
Diversity.PubChemID = data(:,3);

%% Clear temporary variables
clearvars data raw cellVectors;

