% Louise Evans
% Purpose: Print experiment plate maps for this experiment
%% extract info
Selleck.PLATE_384 = categorical(Selleck.PLATE_384);%assign categorical variable
targets = unique(Selleck.Target);
pathways = unique(Selleck.Pathway);
%% Clean up variables 
for z = 1:size(Selleck.Compound_ID,1)
Selleck.Compound_Usage{z} = 'query_cpd';% assign compound usage
Selleck.Dose(z)= 10;% assign 10mM dose
Selleck.UsedWells(z) = 0;% placeholder
Selleck.Cell_Line{z} = '';% placeholder
Selleck.Dose_Category(z)= 1;% highest dose
end
Selleck.Compound_Category = Selleck.Pathway;%repeats this category as possible different uses downstream 
clc
clear z
%% assign row and column indices from well field make plate template
row= cell(size(Selleck,1),1);%preallocate
col= cell(size(Selleck,1),1);%preallocate

for b=1:size(Selleck,1)
    well{b,1} = Selleck.WELL_384{b};%define well
    row{b,1}= well{b}(1:1);% extract row
    rownum{b,1} = strfind('ABCDEFGHIJKLMNOPQ',row{b,1});%convert row letter to number for positional use
    col{b,1}=str2double(well{b}(2:3)); % extract col
end

a = array2table(horzcat(row,col,rownum));% make table of well positions
a.Properties.VariableNames{1} = 'ROW';
a.Properties.VariableNames{2} = 'COL';
a.Properties.VariableNames{3} = 'ROWNUM';
Selleck = horzcat(Selleck,a);%join well positions to table
clear a b well row col rownum %clean

%% reorder the table
% risky as depends on import_compoundplates not changing their order. 
Selleck = Selleck(:,[23 24 13 26 25 22 21 3 14 15 16 5 6 18 17 12 1 2 4 7 8 9 10 11 19 20 27:29]);

%% assign plates for which to make compound maps 
platenames = categories(Selleck.PLATE_384); % compound stock plates
display (platenames)
plate_384 = Selleck.PLATE_384;
SelleckHeaders = Selleck.Properties.VariableNames'; % transpose
platemaps = cell(size(SelleckHeaders,1),size(platenames,1)); % preallocate

for a = 1:size(platenames,1)
    thisplatename = platenames{a,1}; % for each plate
    tablerows = plate_384==thisplatename; % index this plate
    thisplate = Selleck(tablerows,:);% apply index
    thisplate2 = table2cell(Selleck(tablerows,:));% convert to cell - different use
    for d = 1:size(SelleckHeaders,1) % for each sheet to be written
        [template]=LabelPlateMap_LE(); % create template
        template{1,1}=SelleckHeaders{d,1}; % name it accordingly
        for c = 1:size(thisplate,1) % for every compound
            % calculate position
            thisrow = thisplate.ROWNUM{c}+1;
            thiscol = thisplate.COL{c}+1;
            % assign value to position
            template{thisrow,thiscol} = thisplate2{c,d};
        end
        platemaps{d,a} = template; % write the sheets to the platemaps container for each plate
    end    
end

%% write to excel (only works on PC not MAC!!!)
% remove unwanted pages only want the first 16 sheets (extra fields autogenerated previously but we don't want to keep them e.g. SMDC_processed_SMILES)
platemaps2 = platemaps(1:16,:); % choose first 16 fields
SelleckHeaders = SelleckHeaders(1:16,:); % and according headers

% writemaps
% define info on first page (in this case of 10uM compounds)
info = cell(3,1);
info{1,1}= 'Dose Category';
info{1,2}='1';
info{2,1}= 'Dose Format';
info{2,2}='10^-3';
info{3,1}='Dose';
info{3,2}='10';

for a = 1:size(platenames,1) % for each plate
    for e = 1:size(SelleckHeaders,1) % for each field (SelleckHeaders)
        xlswrite(platenames{a,1},platemaps2{e,a},e+1) % write a sheet for each data field
        xlswrite(platenames{a,1},info,1) % write info sheet in the beginning
    end
end
        